"""Centralized styling constants for the application."""

# Colors
COLOR_VENCIDO = "#E74C3C"
COLOR_VENCIDO_BG = "#FADBD8"
COLOR_PROXIMO = "#F39C12"
COLOR_PROXIMO_BG = "#FEF5E7"
COLOR_PROGRAMADO = "#27AE60"
COLOR_PROGRAMADO_BG = "#E8F8F5"
COLOR_COMPLETADO = "#95A5A6"
COLOR_COMPLETADO_BG = "#F2F3F4"

COLOR_SIDEBAR = "#2C3E50"
COLOR_SIDEBAR_TEXT = "#ECF0F1"
COLOR_SIDEBAR_ACTIVE = "#34495E"
COLOR_SIDEBAR_HOVER = "#3D566E"

COLOR_BG = "#F5F6FA"
COLOR_CARD_BG = "#FFFFFF"
COLOR_TEXT = "#2C3E50"
COLOR_TEXT_SECONDARY = "#7F8C8D"
COLOR_BORDER = "#BDC3C7"

COLOR_BTN_PRIMARY = "#3498DB"
COLOR_BTN_PRIMARY_TEXT = "#FFFFFF"
COLOR_BTN_DANGER = "#E74C3C"
COLOR_BTN_SUCCESS = "#27AE60"

# Fonts
FONT_TITLE = ("Segoe UI", 16, "bold")
FONT_SUBTITLE = ("Segoe UI", 12, "bold")
FONT_BODY = ("Segoe UI", 10)
FONT_SMALL = ("Segoe UI", 9)
FONT_CARD_NUMBER = ("Segoe UI", 24, "bold")
FONT_CARD_LABEL = ("Segoe UI", 9)
FONT_SIDEBAR = ("Segoe UI", 11)
FONT_SIDEBAR_TITLE = ("Segoe UI", 13, "bold")

# Dimensions
SIDEBAR_WIDTH = 200
CARD_WIDTH = 160
CARD_HEIGHT = 90
PADDING = 10
